import 'package:flutter/material.dart';
import 'package:routiner/core/constants/default_habits.dart';
import 'package:routiner/l10n/app_localizations.dart';

class LocalizedDefaultHabits {
  static List<DefaultHabit> getGoodHabits(BuildContext context) {
    return [
      DefaultHabit(
        id: 'walk',
        name: context.l10n.translate('walk'),
        emoji: '🚶',
        subtitle: '10,000 ${context.l10n.translate('steps')}',
        color: Color(0xFFFFB3BA),
        targetValue: 10000,
        targetUnit: 'steps',
        unitLabel: 'steps',
        motivation: 'walkMotivation',
        reminderTime: '08:00',
      ),
      DefaultHabit(
        id: 'read',
        name: context.l10n.translate('read'),
        emoji: '📚',
        subtitle: '30 ${context.l10n.translate('pages')}',
        color: Color(0xFFB3E5FC),
        targetValue: 30,
        targetUnit: 'pages',
        unitLabel: 'pages',
        motivation: 'readMotivation',
        reminderTime: '21:00',
      ),
      DefaultHabit(
        id: 'water',
        name: context.l10n.translate('drinkWater'),
        emoji: '💧',
        subtitle: '2,000 ${context.l10n.translate('ml')}',
        color: Color(0xFFB3FFB3),
        targetValue: 2000,
        targetUnit: 'ml',
        unitLabel: 'ml',
        motivation: 'waterMotivation',
        reminderTime: '09:00',
      ),
      DefaultHabit(
        id: 'meditate',
        name: context.l10n.translate('meditate'),
        emoji: '🧘',
        subtitle: '15 ${context.l10n.translate('min')}',
        color: Color(0xFFE5B3FF),
        targetValue: 15,
        targetUnit: 'min',
        unitLabel: 'min',
        motivation: 'meditateMotivation',
        reminderTime: '07:00',
      ),
      DefaultHabit(
        id: 'run',
        name: context.l10n.translate('run'),
        emoji: '🏃',
        subtitle: '5 ${context.l10n.translate('km')}',
        color: Color(0xFFFFD8B3),
        targetValue: 5,
        targetUnit: 'km',
        unitLabel: 'km',
        motivation: 'runMotivation',
        reminderTime: '06:00',
      ),
      DefaultHabit(
        id: 'sleep',
        name: context.l10n.translate('sleepEarly'),
        emoji: '😴',
        subtitle: '8 ${context.l10n.translate('hours')}',
        color: Color(0xFFFFF4B3),
        targetValue: 8,
        targetUnit: 'hours',
        unitLabel: 'hours',
        motivation: 'sleepMotivation',
        reminderTime: '22:00',
      ),
      DefaultHabit(
        id: 'workout',
        name: context.l10n.translate('workout'),
        emoji: '💪',
        subtitle: '45 ${context.l10n.translate('min')}',
        color: Color(0xFFFFB3E5),
        targetValue: 45,
        targetUnit: 'min',
        unitLabel: 'min',
        motivation: 'workoutMotivation',
        reminderTime: '18:00',
      ),
      DefaultHabit(
        id: 'journal',
        name: context.l10n.translate('journal'),
        emoji: '✍️',
        subtitle: '1 ${context.l10n.translate('entry')}',
        color: Color(0xFFB3FFF4),
        targetValue: 1,
        targetUnit: 'times',
        unitLabel: 'times',
        motivation: 'journalMotivation',
        reminderTime: '20:00',
      ),
    ];
  }

  static List<DefaultHabit> getBadHabits(BuildContext context) {
    return [
      DefaultHabit(
        id: 'smoke',
        name: context.l10n.translate('quitSmoking'),
        emoji: '🚭',
        subtitle: '0 ${context.l10n.translate('cigarettes')}',
        color: Color(0xFFFFB3BA),
        targetValue: 0,
        targetUnit: 'times',
        unitLabel: 'cigarettes',
        isGoodHabit: false,
        motivation: 'smokeMotivation',
      ),
      DefaultHabit(
        id: 'social_media',
        name: context.l10n.translate('lessSocialMedia'),
        emoji: '📱',
        subtitle: '1 ${context.l10n.translate('hour')}',
        color: Color(0xFFB3E5FC),
        targetValue: 1,
        targetUnit: 'hour',
        unitLabel: 'hour',
        isGoodHabit: false,
        motivation: 'socialMotivation',
      ),
      DefaultHabit(
        id: 'alcohol',
        name: context.l10n.translate('noAlcohol'),
        emoji: '🍺',
        subtitle: '0 ${context.l10n.translate('ml')}',
        color: Color(0xFFB3FFB3),
        targetValue: 0,
        targetUnit: 'ml',
        unitLabel: 'ml',
        isGoodHabit: false,
        motivation: 'alcoholMotivation',
      ),
      DefaultHabit(
        id: 'procrastinate',
        name: context.l10n.translate('stopProcrastinating'),
        emoji: '⏰',
        subtitle: '1 ${context.l10n.translate('completeTask')}',
        color: Color(0xFFFFB3E5),
        targetValue: 1,
        targetUnit: 'times',
        unitLabel: 'times',
        isGoodHabit: false,
        motivation: 'procrastinateMotivation',
      ),
    ];
  }
}
