// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5iJGVP1byB4LCF9nytwnAbFh-lBgioj8',
    appId: '1:337123515747:web:929f7402922ff8a1538756',
    messagingSenderId: '337123515747',
    projectId: 'routiner-cd119',
    authDomain: 'routiner-cd119.firebaseapp.com',
    storageBucket: 'routiner-cd119.firebasestorage.app',
    measurementId: 'G-CR43TS8N0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8h-0wDsDjuhRwmP9dPtBhjjAzRIfWeqw',
    appId: '1:337123515747:android:4c8da96845be2859538756',
    messagingSenderId: '337123515747',
    projectId: 'routiner-cd119',
    storageBucket: 'routiner-cd119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJfj8EHp0fn43wtTb5j9qx6o573y75zng',
    appId: '1:337123515747:ios:a06386842d1faa80538756',
    messagingSenderId: '337123515747',
    projectId: 'routiner-cd119',
    storageBucket: 'routiner-cd119.firebasestorage.app',
    iosBundleId: 'com.example.routiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJfj8EHp0fn43wtTb5j9qx6o573y75zng',
    appId: '1:337123515747:ios:a06386842d1faa80538756',
    messagingSenderId: '337123515747',
    projectId: 'routiner-cd119',
    storageBucket: 'routiner-cd119.firebasestorage.app',
    iosBundleId: 'com.example.routiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5iJGVP1byB4LCF9nytwnAbFh-lBgioj8',
    appId: '1:337123515747:web:ecc0f32221067ed3538756',
    messagingSenderId: '337123515747',
    projectId: 'routiner-cd119',
    authDomain: 'routiner-cd119.firebaseapp.com',
    storageBucket: 'routiner-cd119.firebasestorage.app',
    measurementId: 'G-P4F8LHX8P6',
  );
}
